name: test1

on: 
    - push
    - workflow_dispatch

jobs:
    create-matrix:
        name: create-${{ matrix.color }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                color: ["red", "blue", "green"]

        outputs:
           color: ${{ steps.create.outputs.color }}

        steps:
            - name: create
              id: create
              run: echo "color=${{ matrix.color }}" >> $GITHUB_OUTPUT

    consume-artifacts:
        runs-on: ubuntu-latest
        needs:
            - create-matrix
        steps:
            - run: echo "${{ needs.create-matrix.outputs.color }}"                
    
    run-2:
        runs-on: ubuntu-latest
        needs: 
            - create-matrix
            - consume-artifacts
        steps:
            - run: echo hi! >> $GITHUB_SUMMARY

    run-3:
        runs-on: ubuntu-latest
        needs: 
            - create-matrix
            - consume-artifacts
        steps:
            - run: echo yo! >> $GITHUB_SUMMARY
