name: test1

on: 
    - push
    - workflow_dispatch

jobs:
    create-matrix:
        runs-on: ubuntu-latest
        outputs:
            colors: ${{ steps.colors.outputs.colors }}

        strategy:
            matrix:
                color: ["red", "blue", "green"]

        name: run-${{ matrix.color }}
        steps:
            - name: echo color ${{ matrix.color }}
              run: echo ${{ matrix.color }} > color

            - name: Produce Artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.color }}
                path: color

    consume-artifacts:
        runs-on: ubuntu-latest
        needs:
            - create-matrix

        steps:
          - name: Retrieve Artifact
            uses: actions/download-artifact@v4
            with:
              merge-multiple: true

          - name: Report Color
            run: ls
