name: test1

on: 
    - push
    - workflow_dispatch

jobs:
    create-matrix:
        runs-on: ubuntu-latest

        outputs:
            color: ${{ steps.create.outputs.color }}

        steps:
            - id: create
              run: echo 'color=["red", "blue", "green"]' >> $GITHUB_OUTPUT

    consume-matrix:
        runs-on: ubuntu-latest
        needs: create-matrix

        strategy:
            matrix:
                color: ${{ fromJSON(needs.create-matrix.outputs.color) }}

        steps:
            - run: echo "${{ matrix.color }}" > file-${{ matrix.color }}.txt
            - uses: actions/upload-artifact@v4
              with:
                path: file-${{ matrix.color }}.txt
                name: file-${{ matrix.color }}.txt
    
    cleanup:
        runs-on: ubuntu-latest
        needs: consume-matrix

        steps:
            - uses: actions/download-artifact@v4
              with:
                path: runs
                merge-multiple: true
            - run: ls -R
              working-directory: runs
