name: test1

on: 
    - push
    - workflow_dispatch

jobs:
    create-matrix:
        runs-on: ubuntu-latest
        steps:
            - run: echo hi

    run-matrix:
        runs-on: ubuntu-latest
        needs: create-matrix
        steps:
            - run: echo ho
    inspect:
        runs-on: ubuntu-latest
        needs: run-matrix
        steps:
            - run: echo oh
