name: test1

on: 
    - push
    - workflow_dispatch

jobs:
    create-matrix:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                color: ["red", "blue", "green"]

        name: create
        steps:
            - run: echo ${{ matrix.color }} > color

            - uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.color }}
                path: color

    consume-artifacts:
        runs-on: ubuntu-latest
        needs:
            - create-matrix

        steps:
          - uses: actions/download-artifact@v4
            with:
              merge-multiple: true

          - run: ls
    
    run-2:
        runs-on: ubuntu-latest
        needs: consume-artifacts
        steps:
            -run: echo hi!
