name: test1

on: 
    - push
    - workflow_dispatch

jobs:
    create-matrix:
        runs-on: ubuntu-latest
        outputs:
            colors: ${{ steps.colors.outputs.colors }}
        steps:
            - name: Define Colors
              id: colors
              run: |
                echo 'colors=["red", "green", "blue"]' >> "$GITHUB_OUTPUT"

    run-matrix:
        runs-on: ubuntu-latest
        needs: create-matrix
        strategy:
            matrix:
                color: ${{ fromJSON(needs.create-matrix.outputs.colors) }}
        name: run-${{ matrix.color }}
        steps:
            - name: echo color ${{ matrix.color }}
              run: echo ${{ matrix.color }} > color

            - name: Produce Artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.color }}
                path: color

    consume-artifacts:
        runs-on: ubuntu-latest
        needs:
            - create-matrix
            - run-matrix
        strategy:
            matrix:
                color: ${{ fromJSON(needs.create-matrix.outputs.colors) }}

        steps:
          - name: Retrieve Artifact
            uses: actions/download-artifact@v4
            with:
              name: ${{ matrix.color }}

          - name: Report Color
            run: cat color
